### ISSUE TITLE
osu!fx Database Incompatibility

### ISSUE THREAD

**Issue by xYahik** [McKay42/McOsu#116]
Hello, in new version - alpha 27, i cant load beatmap i only get this error from debug http://screenshot.sh/m2fYVKRI5Wipi

**Comment by McKay42** [comment]
Hm, error 123 means ERROR_INVALID_NAME and error 5 means ERROR_ACCESS_DENIED.

Peppy osu! can use a separated BeatmapDirectory (separate from the osu!folder where the database and Skins are located), are you using this parameter in your peppy osu!.cfg file (~~not the McOsu! osu.cfg~~)?
(There is definitely something wrong with the paths, since it was able to load the database but couldn't load the beatmaps using the paths stored inside the database.)

Could you please copy paste the entire console log text here?

Also, your database version is way outdated, the current version as of writing this comment is 20170103!
**So please update your peppy osu! client and try again.**

If you are using osu!fx, the database format has been modified there and will not work (you can ask the osu!fx dev to fix it).

**Comment by McKay42** [comment]
rip

**Comment by CIJP** [comment]
Small bump:
I haven't looked into the beatmap database and dont know what is different from the updated version. Any place I can read about this or maybe you can inform me?
_- Emily (Sunpy)_

**Comment by McKay42** [comment]
You are missing the "Size in bytes of the beatmap entry" at the beginning of each "Beatmap Information" entry, see here: https://osu.ppy.sh/wiki/Db_(file_format)

I don't think this value is used anywhere, but it is needed to parse the binary file correctly since peppy osu also has it. You can probably just add a zero integer and it will work fine.

This would be in Beatmap.cs, in the WriteToStream() function.

**Comment by CIJP** [comment]
Many thanks. Will be a while before I get the update out as im still working on alot of changes and have school to worry about aswell >:L
But thanks ^.^
_- Emily (Sunpy)_
