### ISSUE TITLE
Fix Big MP3s

### ISSUE THREAD

**Issue by McKay42** [McKay42/McOsu#121]
e.g. https://osu.ppy.sh/b/1003401

BASS_SampleLoad() will not load files over a certain size (?), must use BASS_StreamCreateFile() instead. This however breaks seeking somehow.

**Comment by nallar** [comment]
Some more broken maps with big mp3s, presumably due to this:

[Within Temptation - The Unforgiving](https://osu.ppy.sh/s/29157) - 53 minutes
[TERRA - Dance Dance Revolution NON STOP MEGAMIX](https://osu.ppy.sh/s/2228) - 26 minutes
[Renard - Because Maybe! pt. 2](https://osu.ppy.sh/s/149471) - 22 minutes
[Knife Party - Songs Compilation](https://osu.ppy.sh/s/123040) - 19 minutes

**Comment by McKay42** [comment]
Solution: Prefer BASS_SampleLoad(), but fall back to BASS_StreamCreateFile() with BASS_STREAM_PRESCAN if SampleLoad fails. As soon as SampleLoad fails once, set a flag to always use StreamCreateFile (within this session, for this beatmap).

This means that there is still quite a long loading time until SampleLoad fails, but all subsequent calls will be quick after the flag is set.

A sideeffect of BASS_STREAM_PRESCAN is that even a stream now takes some time to load, so there will be a bigger delay when selecting the beatmap again in the songbrowser, but it's negligible and only affects very few very long beatmaps.
