### ISSUE TITLE
[VR] Add ghost of hit objects on play screen

### ISSUE THREAD

**Issue by ShadowFoxNixill** [McKay42/McOsu#134]
I just tried this out upon a recommendation from a friend in VR. It was fun, and my arm is sore, but I have one major problem: I don't know where the hit objects are going until they land on the screen, and by then I've already clicked someplace else. What I'd like to see is a ghost of the object's final position on the screen as flies in, so I can position my controller accordingly.

**Comment by McKay42** [comment]
I'll probably add approach circles (aka ghost hitobjects) as an option in the future, but please read on:

You're probably too far away from the playfield, or have it scaled too big/small. Maybe also try overriding the Approach Rate to make things a bit slower/easier to read.
See my tutorial video here: https://www.youtube.com/watch?v=9VhYIUUltGI

After you've set the playfield to match your height and arm length, don't focus or look at where the hitobjects will land, focus on the horizon so that you can "read ahead". You can see in the video that I'm almost never looking directly at close hitobjects, and if the size of the playfield is set correctly I can easily estimate how far to move my arms. (You basically shouldn't focus on the playfield plane at all as you _will_ play way worse if you do so)
I might be a bit biased since I have played osu! for a long time now, so general reading skills and rhythm predicition (especially slider velocities and distance-to-time estimation) are something new players will only aquire slowly over time.
