### ISSUE TITLE
"Click on the orange circle to continue playing" not working as intended

### ISSUE THREAD

**Issue by MaxKruse** [McKay42/McOsu#142]
as seen [here](http://lithibae.s-ul.eu/qAXLElg5), the graphic is missing in the steam version, as well as not functioning as intended. doesnt matter where u click, it registers it.

**Comment by McKay42** [comment]
the missing texture thing has happened for quite some time, I've yet to invest time in finding out what causes it. See > https://github.com/McKay42/McOsu/issues/83
you can click anywhere on purpose, because restricting it seems useless (if you want to practice then just force yourself to click inside the circle)
