### ISSUE TITLE
Depth for sliders in VR?

### ISSUE THREAD

**Issue by nallar** [McKay42/McOsu#147]
Would it make sense to give sliders depth in VR?

The part of the slider your hand should be at would reach the front of the playfield at the time you should be over it.

(I have completely failed at explaining that clearly)

**Comment by McKay42** [comment]
I understand what you mean, and you're not the first to suggest this :)

Generating the meshes is going to be quite tricky, and I don't yet know how to make them look good when they have depth:
Currently the sliders in VR are rendered with a bit of a trick to directly use a mesh that even allows hardware antialiasing to work (instead of rendering them to a flat texture and then drawing that image as the slider, which would look like shit up close due to limited texture resolution).
This trick however only works because the sliders are 2D (mostly).
It would be a lot easier by making the sliders look different, but I want to keep the style the same.

Gameplay-wise I'm not sure what effect this would have, e.g. maybe circles directly under the end of a slider would be harder to read? There would be an option to enable or disable it of course.
