### ISSUE TITLE
i launch mcosu on steam (both steamvr and desktop) but it wont open :(

### ISSUE THREAD

**Issue by TheHypeGamer** [McKay42/McOsu#166]
this shit is really annoying and i want it to stop. can you please fix this? mcosu wont even open whne i click play.

**Comment by McKay42** [comment]
Right click the game in your library > Properties > Local Files > Verify Integrity of Game Files.
If files are missing, then your antivirus may have deleted the executable, because it's not signed and most antiviruses automatically flag every unsigned executable as evil.

If that is not the case, right click the game in your library > Properties > Local Files > Browse Local Files, and try to launch McEngine.exe. If that doesn't work, try to launch McEngine_Debug.exe and check the console window log for what is happening.
