### ISSUE TITLE
Hitsound of next map section gets ignored (increases to 100%) when tab out

### ISSUE THREAD

**Issue by IrixOException** [McKay42/McOsu#184]
If you tab out of McOsu the hitsound volume of the next beatmap will be ignored (or is always at 100% vol) until it reaches a point where the volume changes (back to normal).
If you have not reached a point and retry the map the volume is still at 100% (does not update with retry)

**Comment by McKay42** [comment]
I can't reproduce this, do you have a specific beatmap where it always happens?

**Comment by IrixOException** [comment]
https://osu.ppy.sh/beatmapsets/53791#osu/171927

I noticed it with this one on easy diff 'cause right at beginning on the end of second slider the volume changes to normal.
It happens on every map tho

Heres a vid https://puu.sh/AcEXd/d32523249c.mp4

**Comment by McKay42** [comment]
Thanks, just managed to also reproduce it on The Empress, no idea why it didn't work yesterday.
https://osu.ppy.sh/beatmapsets/328780

This seems to be a bug in the BASS audio library, because there is no game logic which would affect sample volumes on window focus changes. Reason being that BASS is initialized with the window handle (on Windows).

Should be easy enough to fix by simply always resetting the sample volume in onFocusGained().

**Comment by McKay42** [comment]
Is fixed, restart Steam to force update.
