### ISSUE TITLE
"Access is denied." (0x5)

### ISSUE THREAD

**Issue by iOppy** [McKay42/McOsu#195]
This is the only game in my steam library that provides this issue, and I have even tried going into the files manually and setting them to run as administrator, but that attempt was unsuccessful to fix it.

Have no clue what is causing this since no other game I own does this and my Steam Library is even outside Program Files since that caused issues with me in the past. So McOsu is the only game I have seen this with ever since I had this issue a year ago with my Steam Library.

https://i.imgur.com/XgyFkCW.png -- Here is the screenshot of the error I recieve, also just as a note I am NOT running this as VR Mode since I am trying to run it in normal desktop mode to practice my Osu! maps...

Thanks,

~Oppy

**Comment by McKay42** [comment]
This is probably related to antivirus software locking the executable because it's not signed, and you're not the only one (nor is this the only game where it happens).

Simply google "steam launch game access is denied 0x5" and try a few things:

If you fully trust the executable, you can tell your antivirus software to leave it alone (i.e. add an exception).
Also, check if the Windows file system security permissions are correct for the executable (execution should be allowed for your local user or the group you are in, i.e. "Read & execute").
Try running the executable directly, without using steam (/<Steam>/steamapps/common/McOsu/McEngine.exe).
Try temporarily enabling side-loading of apps, if you are on Windows 10.

Please use google before creating an issue.
