### ISSUE TITLE
slidergradient.png doesn't get tinted

### ISSUE THREAD

**Issue by LastExceed** [McKay42/McOsu#210]
in the default skin the slider track always gets tinted in either the combo color whatever color the user specified using `SliderTrackOverride` in the skin.ini

This tinting should also but isn't applied when the user makes use of slidergradient.png

-----

coloring is applied to the body here: https://github.com/McKay42/McOsu/blob/master/src/App/Osu/OsuSliderRenderer.cpp#L177

but (for whatever reason) only if slidergradient.png isn't used. I figured fixing this should be as easy as applying that line to all sliders instead of just default sliders, but I'm not a cpp programmer so I can't try this myself.

**Comment by McKay42** [comment]
You misunderstood the feature, it's supposed to completely replace the entire slider body with the slidergradient texture stretched out. Obviously any dynamic properties don't work then anymore, since the game can't know which parts of the gradient image you deem as being part of the border vs body vs shadow.

If you want something more complex than the existing customization options (border width, color, opacity, osu!next style, combo color tint, saturation), you'll have to modify the slider pixel shader manually: https://github.com/McKay42/McOsu/blob/master/build/shaders/slider.fsh
