### ISSUE TITLE
Exit to score screen instead of pausing if no hitobjects remaining

### ISSUE THREAD

**Issue by sourcandy** [McKay42/McOsu#216]

**Comment by McKay42** [comment]
Will be included in the next update on Steam.
New ConVar: osu_end_skip_time
Default value is 400 (ms), since osu! also gives you a short window in which you can still pause after the last hitobject is finished. Previously this was 1250 (ms), now the pause-immediately-skips-to-ranking-screen delay and wait-a-little-bit-at-the-end-of-the-beatmap-before-showing-the-ranking-screen delay are separated, osu_end_skip_time and osu_end_delay_time.
