### ISSUE TITLE
FPoSu Invert Y

### ISSUE THREAD

**Issue by inv41idu53rn4m3** [McKay42/McOsu#238]
FPoSu needs to have an option for inverting the Y axis since some people like me are used to it and can't aim properly without it.

**Comment by McKay42** [comment]
Options > FPoSu > FPoSu - Mouse > "Invert Vertical"
Options > FPoSu > FPoSu - Mouse > "Invert Horizontal"

**Comment by inv41idu53rn4m3** [comment]
Okay I'll just have to go check if I'm blind or not. I apologize for the pointless issue.

**Comment by inv41idu53rn4m3** [comment]
Scratch that. After checking the code it seems you made that option Windows specific. I see no reason for that though... Unless it's due to some input library features.

**Comment by McKay42** [comment]
> 
> 
> Scratch that. After checking the code it seems you made that option Windows specific. I see no reason for that though... Unless it's due to some input library features.

Ah yes, sorry, forgot about that.

Proper raw mouse delta support is not yet implemented in the engine for Linux, since that functionality is very annoying/unclear/undocumented, and I don't want to have an incorrect implementation (it must match Windows _exactly_).

The current status is that XInput2 XI_RawMotion should give XIRawEvent::raw_values, but then you don't get any events if any mouse button is clicked and other random fun behavior, so I need to invest more time and test this thoroughly on different distros etc. etc.

**Comment by inv41idu53rn4m3** [comment]
Guess I'll have to keep using the workaround of using xinput to invert my mouse movement globally. Guess I could even automate it through window manager shenanigans...
