### ISSUE TITLE
BPM HUD still stuck highest BPM

### ISSUE THREAD

**Issue by NixXSkate** [McKay42/McOsu#242]
I saw this mentioned in the patch notes and earlier issues, but it seems that the BPM HUD is still only showing the highest bpm value of the map at all times rather than the BPM it is currently in the song.

**Comment by McKay42** [comment]
That is its intended function.
The bug fixed was related to the speed multiplier affecting displayed BPM too late.

You can't use the active timingpoint for displaying BPM, because it would jump around constantly due to slider velocity changes, and be generally useless. All other methods of dynamically calculating BPM from live beatmap data are inconsistent, as there is no reference point.
