### ISSUE TITLE
Game minimizes when I change volume in KDE

### ISSUE THREAD

**Issue by veronikazaglotova** [McKay42/McOsu#279]
- Plasma 5.17.5
- Linux 5.4.42
- Distribution: NixOS
At first I though that I'll make an issue on KDE bugtracker but I saw that there was an issue with Minecraft already https://bugs.kde.org/show_bug.cgi?id=396988 and they say that it was a bug with Minecraft

**Comment by McKay42** [comment]
The game has no power over what your operating system does when the volume is changed.
The volume is changed via the BASS audio library function call `BASS_SetConfig()`.

If the game window loses focus, because your operating system tells it to lose focus, because the operating system wants to draw some kind of volume slider overlay which eats inputs, then that is a problem of your operating system (and _not_ the game).

**However**, you can force change the default focus loss behavior of the engine, by using these convars:
`minimize_on_focus_lost_if_fullscreen 0`
`minimize_on_focus_lost_if_borderless_windowed_fullscreen 0`

Read the FAQ on how to use the in-game console: https://steamcommunity.com/app/607260/discussions/0/1620599015885400990/
