### ISSUE TITLE
Unstable rate is probably not multiplied when using DT or HT

### ISSUE THREAD

**Issue by veronikazaglotova** [McKay42/McOsu#285]
https://osu.ppy.sh/help/wiki/Accuracy
Here ppy says that when you are using DT unstable rate is multiplied by 1.5 and divided by 1.33. So, to get real unstable rate of a run that I played with DT I have to divide unstable rate by 1.5.
I just had a run where I had 180 unstable rate with DT, which means that real unstable rate is 120. Normally, I would have around 200-400 unstable rate, there is no way I could have 120 unstable rate. Please fix...

**Comment by McKay42** [comment]
McOsu shows speed-compensated UR, because that makes sense:

```
// compensate for speed
m_fUnstableRate /= beatmap->getSpeedMultiplier();
```
(Relevant code in [Score.cpp](https://github.com/McKay42/McOsu/blob/master/src/App/Osu/OsuScore.cpp#L294))

The fact that osu! is not compensating the displayed UR value is stupid and should be changed.

To get the uncompensated osu! UR from a McOsu UR, just multiply by the speed multiplier.
In this case, your 180 McOsu UR is equal to 270 osu! UR.

**Comment by veronikazaglotova** [comment]
Based. Thanks a lot
