### ISSUE TITLE
Use osu! default hitsounds instead of your current default skin's

### ISSUE THREAD

**Issue by MaxKruse** [McKay42/McOsu#288]
I dont know why, but there is no way with the options to make hitsounds on maps appear exactly as they are intended to on osu! stable. The default skin on McOsu has these weird clack clack hitsounds that are not default at all. pls fix

**Comment by McKay42** [comment]
Unfortunately, that's not how the world works.

I can't just copy osu!'s default hitsounds, because that would be blatant copyright infringement, keeping in mind that peppy doesn't even like people reuploading the default skin template to third party sites.

1. Go read the [LICENSE](https://osu.ppy.sh/community/forums/topics/129191) for the osu! default skin template.
2. Just create your own skin mixed with whatever hitsounds you always want to have.

Relying on default hitsounds is bad, and subject to change with osu updates, so stop doing that.
