### ISSUE TITLE
Skin overide problem on 31.11

### ISSUE THREAD

**Issue by Sowlokt** [McKay42/McOsu#291]
So when I started McOsu after the 31.11 update today I noticed something strange about the menu.

The way the `selection-mods@2x.png` and `selection-random@2x.png` buttons were displayed changed [https://imgur.com/UkqDWWn](url)

Also the score numbers and `x` are now displayed incorrectly with only that particular skin (skin_1) [https://imgur.com/T0CdHXU](url),
the score-x@.png is used in McOsu (instead of score-x@2x.png on osu!) and it seems that McOsu is mixing its own score numbers with the one from the skin [https://imgur.com/TfofC7C](url).

It appears that all I described above doesn't happen with another skin I tried (skin_2), one of WhiteCat's [https://imgur.com/qZE0rZr](url), even though the score-numbers files names are the same as skin_1.

After some digging I found out that skin_1 has `scoreentry-x.png`, `scoreentry-x@2x.png`, `score-x.png`, `score-x@2x.png` for the combo `x`. I'm not sure which of the files it uses to display combo numbers.
And skin_2 seems to use `combo-x.png`, `como-x@2x.png` and the different combo numbers like `combo-0.png`. 

Osu! seems fine with handling all these different names but maybe McOsu is struggling with those ? Or I could totally be wrong about that. 

Thank you for your time and efforts for McOsu, McKay!

Edit :
I should add that the skin_1 concerned is Shigetora's 21.7 from https://gist.github.com/Fobxx/107e2bad2bf7312cd49431c696aac912

Also the bugged `combo-3.png` problem also seems to appear for the accuracy tracker.

**Comment by McKay42** [comment]
1) Enable Options > Skin > "Load HD @2x" to fix everything.
2) osu! _always_ has "Load HD @2x" enabled if your resolution is >= 1600x1200, so a lot of skins break when played at lower resolutions, because people don't know that osu! is doing this. Try playing osu! in 1024x768, the skin will be broken in the exact same way.

![Capture](https://user-images.githubusercontent.com/16856443/91643218-84c4ab80-ea31-11ea-8818-ec490eaf6e55.PNG)


Skin problems I've noticed:

- Invalid filenames (`score-3@.png` should be `score-3.png`)
- Mismatched skin elements between regular and @2x files (e.g. `score-x.png` is red and `score-x@2x.png` is grey)
- Missing skin elements (only `selection-random@2x.png` exists, so `selection-random.png` is missing) causing default skin fallback because you deliberately disabled "Load HD @2x" in options
