### ISSUE TITLE
Collections are broken

### ISSUE THREAD

**Issue by cptslow-osu** [McKay42/McOsu#297]
Collections in McOsu display full Beatmapsets instead of the individual maps selected, making them extremely impractical in some  use cases and unusable in the majority of use cases (such as having collections with stream maps at a certain BPM to practice). Since the md5 hash in the collection.db file links directly to the difficulty's .osu file this should be an easy fix.

Edit: what I mean by this is adding a toggle to remove the additional logic that fetches the beatmapset's remaining difficulties should be easy

**Comment by McKay42** [comment]
This is a long standing limitation of the old songbrowser/db/ui implementation, I'm already working on a [rework](https://github.com/McKay42/McOsu/tree/rewrite) which supports individual diff buttons without parents (among other things).

For the current build on Steam this is still expected behavior: Maps which are part of the "real" collection get their button colored orange. While this doesn't help with beatmaps which have over 9000 diffs, it's at least something.

> 
> this should be an easy fix.

No, unfortunately not.
