### ISSUE TITLE
Feature Request: Ability to lock BPM

### ISSUE THREAD

**Issue by Thymue** [McKay42/McOsu#300]
Maybe with a lock like for AR&OD you'll be able to lock bpm so every map's speed multiplier will then adjust to that bpm

**Comment by McKay42** [comment]
Unfortunately the game doesn't work like that:

- The BPM value shown in the songbrowser is solely derived from the slider velocity in timingpoints (very simply put).
- The BPM value varies wildly inside one single beatmap (which is why the songbrowser shows you a BPM range, e.g.: 120 - 360). Some beatmaps even have BPM changes _for every single slider_.
- Circles have no correlation to BPM whatsoever. A circle is "hardcoded" to a specific point in time where you have to click it. There is _nothing else_.
- Due to already mentioned random changes in BPM throughout a beatmap, the speed multiplier would have to randomly change with it to compensate, and due to how timingpoints are placed in beatmaps this is unplayable (believe me, I have tested it).
