### ISSUE TITLE
Error: Couldn't load beatmap metadata

### ISSUE THREAD

**Issue by mmitteregger** [McKay42/McOsu#328]
Some beatmaps don't load and can't be played.

I think the problem is a combination of:
* OS: Linux
* Unplayable Beatmap files are in a subdirectory inside the `Songs` directory.
  Example: `<osu_dir>/Songs/__Stream Maps/277421 Lindsey Stirling - Senbonzakura [no video]/`

Reduced log excerpt (replaced <osu_dir>, removed duplicates, ...):
```log
Resource Manager: Loading <osu_dir>/Songs/427508 Wagakki Band - Senbonzakura/BG.png
Resource Warning: File <osu_dir>/Songs/__Stream Maps\277421 Lindsey Stirling - Senbonzakura [no video]/Senbonzakura - Lindsey Stirling.mp3 does not exist!
Resource Manager: Loading <osu_dir>/Songs/__Stream Maps\277421 Lindsey Stirling - Senbonzakura [no video]/senbonzakura - lindsey stirling.mp3
Couldn't load sound "<osu_dir>/Songs/__Stream Maps\277421 Lindsey Stirling - Senbonzakura [no video]/senbonzakura - lindsey stirling.mp3", stream = 1, errorcode = 5, file = <osu_dir>/Songs/__Stream Maps\277421 Lindsey Stirling - Senbonzakura [no video]/senbonzakura - lindsey stirling.mp3
File Error: Couldn't open() file <osu_dir>/Songs/__Stream Maps\277421 Lindsey Stirling - Senbonzakura [no video]/Lindsey Stirling - Senbonzakura (MrSergio) [Extra].osu
Osu Error: Couldn't read file <osu_dir>/Songs/__Stream Maps\277421 Lindsey Stirling - Senbonzakura [no video]/Lindsey Stirling - Senbonzakura (MrSergio) [Extra].osu
Osu Error: Couldn't load beatmap metadata <osu_dir>/Songs/__Stream Maps\277421 Lindsey Stirling - Senbonzakura [no video]/Lindsey Stirling - Senbonzakura (MrSergio) [Extra].osu
```

Notice the backslash `\` after the `__Stream Maps` directory instead of the forward slash `/` as path separator.

I don't know where this error originates from.
A simple quick and dirty fix would be fixing of the file path inside [Resource.cpp](https://github.com/McKay42/McEngine/blob/01224ebd4df73b6636a8e657c241c8eef951f1a5/McEngine/src/Engine/Resource.cpp#L12) and [File.cpp](https://github.com/McKay42/McEngine/blob/e6efd9077723d794d7472a4d72281e92db49168c/McEngine/src/Engine/Platform/File.cpp#L85).

**Comment by McKay42** [comment]
> Reduced log excerpt (replaced <osu_dir>, removed duplicates, ...)

Please don't do that, makes it harder for me to diagnose. Anonymizing usernames etc. is fine, but don't replace the _entire_ path. Also, always post/attach the _entire_ log.

> <osu_dir>/Songs/427508 Wagakki Band - Senbonzakura/BG.png
> <osu_dir>/Songs/__Stream Maps\277421 Lindsey Stirling - Senbonzakura [no video]/Senbonzakura - Lindsey Stirling.mp3 does not exist!
> I don't know where this error originates from.

1. Does the folder `<osu_dir>/Songs/__Stream Maps/277421 Lindsey Stirling - Senbonzakura [no video]/` exist?
2. I assume you have an existing osu! database this is being read from? Because otherwise the backslash is impossible.
The osu!.db file this is being read from would contain the `__Stream Maps\277421 Lindsey Stirling - Senbonzakura [no video]` part, the game then goes and inserts `<osu_dir>/Songs` at the beginning and a filename at the end. Peppy wrote osu!stable for Windows only, which is why it can happen to have backslashes stored in filepaths in its database.
3. I will add an edge case to replace all backslashes with forward slashes (in whatever string is being read from the osu!.db file).
4. Just in case you didn't know, nested beatmap folders are _usually_ **not** supported:

Bad = `<osu_dir>/Songs/__Stream Maps\277421 Lindsey Stirling - Senbonzakura [no video]/Lindsey Stirling - Senbonzakura (MrSergio) [Extra].osu`

Good = `<osu_dir>/Songs/277421 Lindsey Stirling - Senbonzakura [no video]/Lindsey Stirling - Senbonzakura (MrSergio) [Extra].osu`

If you use osu! normally then it is impossible to create nested beatmap folders, because the game handles all the osz extraction and file copying for you. Please just let the game do its thing without manually fiddling around in the Songs folder.

If you followed the [guide](https://steamcommunity.com/sharedfiles/filedetails/?id=880768265) for manual beatmap management, then you would not have created nested beatmap folders either.

But, in your specific case, where you have an existing osu!.db with such weird paths, it will work once the workaround is in place (assuming the files actually exist in those nested subfolders of your filesystem).

**Comment by McKay42** [comment]
f8f90d6687512616220fb079b6190e3607508b16

**Comment by mmitteregger** [comment]
Sorry about the log reduction. I tried to be helpful by reducing the noise while maintaining the relevant information. I'll post the full log in the future.

About your questions:
1. Yes, the folder `<osu_dir>/Songs/__Stream Maps/277421 Lindsey Stirling - Senbonzakura [no video]/` does exist.
The beatmaps also correctly load with osu!stable (on Windows or via wine).
2. I didn't know about that. I have verified that the `osu!.db` contains the folder paths with these backslashes, so that's were the problem originated from.
3. Thanks for the quick fix.
4. I have reused the Songs folder from my previous osu!stable installation on Windows. Sorry for the trouble.

I've verified the fix locally, awesome! Thanks again! :heart:
