### ISSUE TITLE
HP Drain

### ISSUE THREAD

**Issue by Toyeonjeangikkingkkang** [McKay42/McOsu#334]
Hello, McKay42. How can freely adjust the speed of the HP Drain reduction rate at will, regardless of spinner additions, spinner duration, new combos, note density, OD, etc. in McOsu?

**Comment by Toyeonjeangikkingkkang** [comment]
> Hello, McKay42. How can freely adjust the speed of the HP Drain reduction rate at will, regardless of spinner additions, spinner duration, new combos, note density, OD, etc. in McOsu?

**Comment by McKay42** [comment]
> Hello, McKay42. How can freely adjust the speed of the HP Drain reduction rate at will, regardless of spinner additions, spinner duration, new combos, note density, OD, etc. in McOsu?

I've already explained it to you on the osu! forums [here](https://osu.ppy.sh/community/forums/topics/1544489?n=5).
But since we appear to be having a bit of a language barrier problem I'll repeat myself:

If you want **no** constant drain and fixed drain amounts per hit regardless of OD and HP, then use the VR drain:
![Capture](https://user-images.githubusercontent.com/16856443/160233902-8a93be94-f13d-4801-bbd1-7b87c5cbe6bf.PNG)
And customize the drain amounts via `osu_drain_vr_multiplier`, `osu_drain_vr_300`, `osu_drain_vr_100`, `osu_drain_vr_50`, `osu_drain_vr_miss` and `osu_drain_vr_sliderbreak`.

If you want constant drain and again fixed drain amounts per hit regardless of OD and HP, then use the osu!lazer 2020 drain:
![Capture2](https://user-images.githubusercontent.com/16856443/160234047-a05c065a-debf-4170-b0aa-537ff2067493.PNG)
And customize the drain amounts via `osu_drain_lazer_multiplier`, `osu_drain_lazer_300`, `osu_drain_lazer_100`, `osu_drain_lazer_50`, `osu_drain_lazer_miss`, `osu_drain_lazer_health_min`, `osu_drain_lazer_health_mid`, `osu_drain_lazer_health_max`.

It's probably a good idea to experiment with different values on your computer with the [PC version of McOsu](https://store.steampowered.com/app/607260/McOsu/), instead of on your Nintendo Switch, and then transfer the values once you have found ones you like.

Also this is not what Github is intended for, if you have support questions then it's better to ask in the [McOsu Discord](https://discord.gg/3UQnt7X) or the [McOsu Steam Forums](https://steamcommunity.com/app/607260/discussions/).
