### ISSUE TITLE
McOsu doesn't start and crashes even after uninstalling and reinstalling

### ISSUE THREAD

**Issue by ikkue** [McKay42/McOsu#342]
Exactly like the title says. Here's video proof

https://user-images.githubusercontent.com/11213135/198309513-758463d0-150a-411b-a87a-f17a9332838b.mp4

Here are my specs
![image](https://user-images.githubusercontent.com/11213135/198309579-996d551e-40a4-4c26-b1ab-3b9775583164.png)

I have both osu!(stable) and osu!(lazer) installed. I use OpenTabletDriver as my tablet driver.

**Comment by McKay42** [comment]
Follow these steps in order:

1. Steam > Library > right click on McOsu > Properties > Local Files > click on "Browse..."
2. In the explorer window that just opened, go into the `cfg` folder
3. Inside the `cfg` folder, rename the "osu.cfg file to "osu_old.cfg"
4. Steam > Library > right click on McOsu > Properties > Local Files > click on "Verify integrity of game files..."
5. Let it download whatever it needs to download
6. Try starting McOsu from Steam again as usual, if it still does not work then continue
7. Run `cmd.exe` as administrator
8. Enter this command: `sfc /scannow` (source: [here](https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e), because your error code seemed suspicious)
9. Let the command finish, then reboot, then try starting McOsu. If it still does not work then check if the error has changed.

**Comment by ikkue** [comment]
It worked! Thank you very much.

**Comment by ikkue** [comment]
It worked! Thank you very much.
