### ISSUE TITLE
McOsu freezing 

### ISSUE THREAD

**Issue by lovverrr** [McKay42/McOsu#347]
After playing 2-3 maps McOsu starts freezing for a little period of time while playing a map and it's very uncomfortable to play. Is there any solutio?

**Comment by McKay42** [comment]
1) Post your pc specs (OS, CPU, GPU, RAM, driver versions, etc.)
2) This is caused by either your graphics driver and/or something running in the background.
3) Hit CTRL + F11 to open the frametime graph, then take note which colored bar is the highest/largest when you have such a freeze (or just after the freeze when you can see a big bar appear on the graph) and report back here.
4) Open Task Manager and sort by CPU usage, look at it on a second monitor when you have such a freeze to note which process is potentially freezing the game. Also try sorting by GPU usage and doing the same thing.
5) Disable all crappy garbage overlays like Nvidia/Discord overlay and try all of that again.
6) Disable all external FPS limiters (like RivaTuner etc.) or other interfering software, disable all overclocks, close all other programs and try all of that again.

**Comment by McKay42** [comment]
Any updates on this?

**Comment by McKay42** [comment]
(Feel free to respond still, but I'm not leaving this open)
