### ISSUE TITLE
spinner-background.png is not being drawn

### ISSUE THREAD

**Issue by resolritter** [McKay42/McOsu#352]
I think `spinner-background.png` is not being drawn. My conclusion comes from this part of the code:

https://github.com/McKay42/McOsu/blob/2f22a941b84d093614a27bb255defb7a76dfc5aa/src/App/Osu/OsuSpinner.cpp#L99

The code checks if `spinner-background.png` was loaded (`skin->getSpinnerBackground() != skin->getMissingTexture()`), but apparently doesn't do anything with the asset within the `if`'s body.

Reference: https://osu.ppy.sh/wiki/en/Skinning/osu%21

**Comment by McKay42** [comment]
The check is only used to detect old style spinners in skins, which are not implemented/supported. Everything inside the if-block for the "old style" spinners is just a workaround so skins with old style skins show _something_ playable at all instead of being invisible.

Unless you intend to write the code for supporting old style spinners **fully** properly this is not going to change.
