### ISSUE TITLE
[Feature Request] Slider Speed Override

### ISSUE THREAD

**Issue by TyroneBarkley** [McKay42/McOsu#355]
It would be amazing if you were able to add a **Slider Speed Override** to the mods menu. To clarify I'm not talking about the actual sliders of the setting where you are able to move the circle across the line to incremently change the values. I'm referring to the osu! sliders in game that function as hit objects. The designer of an osu map is the person responsible for how fast they want the sliders to be, and they are also able to have two different slider speeds in the same map to act as a sort of tempo shift. It's hard to change the speed of every individfual slider without changing the actual map itself, but a **Slider Speed Override** would allow to have a consistent speed for all the sliders, which is not perfect but can work. 

Obviously the Slider Speed Sverride wouldn't be effective in some maps, however it is a very useful tool to be able to tamper with, especially because it might create some variance in dificulties ex: if the author of a map has only created a **10 Star** version of a song, the Slider Speed Override might be able to essentially create a **4 Star** version of the song which hasn't been mapped yet. 

This small change would help drastically in some cases, and probably would not take a lot of effort to implement, so please consider it. 

Example Of Sliders
![Sliders](https://user-images.githubusercontent.com/104330990/223335155-eb12fc77-4dd1-4dc9-9ee7-ba04105666c0.jpg)

Example Of Change
![SS Override](https://user-images.githubusercontent.com/104330990/223334960-ab0fcc7e-84bf-4b2c-8060-495bbc96696f.png)

**Comment by McKay42** [comment]
> and they are also able to have two different slider speeds in the same map

You can have infinitely many different slider speeds on the same beatmap. Slider speed is defined by the [beatmap timingpoints, and uninherited timingpoints can set any arbitrary slider speed multiplier through a negative beat length value](https://osu.ppy.sh/wiki/en/Client/File_formats/Osu_%28file_format%29#timing-points).
See [this beatmap on the [Maze] difficulty](https://osu.ppy.sh/beatmapsets/537048#osu/1529759) for example.

> It's hard to change the speed of every individfual slider without changing the actual map itself, but a Slider Speed Override would allow to have a consistent speed for all the sliders, which is not perfect but can work.

Unfortunately, rhythm and music don't work like that. What I mean is that the beatmap has fixed points in time (relative to the absolute music playback position) where things happen _in time with the beat and melody/percussion_, like a slider ending, and changing that will either break all hitobjects after that slider (because of overlapping, you can't "push" the beatmap back) or feel extremely weird if the slider finishes way too early compared to the rhythm (even if it is technically "in time with the beat").

- Making sliders slower will make them intersect with all hitobjects after the original end of the slider. This is unplayable.
- Making sliders faster or reducing their number of repeats will break rhythm flow. This will feel extremely bad to play because you are introducing [syncopes/off-beat](https://en.wikipedia.org/wiki/Syncopation) hits.
- Making sliders physically shorter or longer will either make them intersect with other hitobjects or break rhythm flow and [beat spacing](https://osu.ppy.sh/wiki/en/Client/Beatmap_editor/Distance_snap).

If you were to try what you suggested right now, within 30 seconds you would say "this feels like crap, useless and unplayable" and never use that feature again.

> if the author of a map has only created a 10 Star version of a song, the Slider Speed Override might be able to essentially create a 4 Star version

You are **vastly** overestimating how much sliders contribute to star rating. Sliders only have to be hit at the start, ticks, repeats, and the end. Anything in-between is completely ignored by the game (you can move the cursor outside the slider, stop pressing keys, etc.), see [this example](https://youtu.be/NxzYup6-Umo?t=233).
