### ISSUE TITLE
Mouse movements are too smooth?

### ISSUE THREAD

**Issue by jameshi16** [McKay42/McOsu#36]
Hey

Maybe it's just my imagination, but for some reason, I feel the cursor smoothing when trying to aim with a mouse. Turning off Raw Input seems to make the mouse snappier, but perhaps it is my imagination?

**Comment by McKay42** [comment]
It's due to the mouse acceleration which you get in Windows without raw input, it does make it seem snappier (but your aim gets destroyed in the process, and you can never build proper muscle memory).

Raw input takes the movement values more or less directly from the sensor of the mouse, without any modifications, and might therefore look a bit different depending on the polling rate of the sensor, the polling rate of the USB connection and how the mouse driver handles things.

There is no mouse smoothing or acceleration applied anywhere if you have raw input enabled, the code boils down to pretty much this:
`NextCursorPosition = CurrentCursorPosition + (RawMouseDelta * Sensitivity)`

**Comment by jameshi16** [comment]
Ah, my bad, I turned on adaptive V-sync the other day and forgot about it.

For anyone experiencing the same problem, adaptive V-sync (or any other V-sync setting) really screws up perceived mouse latency, so don't use it!
