### ISSUE TITLE
Skin Rendering Problems

### ISSUE THREAD

**Issue by Zripzri** [McKay42/McOsu#367]
Many skins don't draw correctly in several places. 
For example https://osu.ppy.sh/community/forums/topics/680124?n=1
In this case:
- On song select, "mode" and "options" don't draw correctly (the skin uses a wide banner and it is scaled to fit into the small rectangle).
- In the score screen numbers are reversed (e.g. 81 instead if 18) and are misaligned (probably offset sign error?)
- In game the combo counter only shows the first digit (could be the same bug as above, other digits are drawn off screen).

Version: 33.06 (it has been there for a while, sadly I don't remember when it first appeared)
OS: Arch Linux

![image](https://github.com/McKay42/McOsu/assets/67809887/a80e5274-5d4a-4803-bdc1-138ddd741e5f)
![image](https://github.com/McKay42/McOsu/assets/67809887/cfaa2ced-bd0d-43cb-a4c5-f34891403e88)
![image](https://github.com/McKay42/McOsu/assets/67809887/5ece4437-0be8-41a1-b9f2-42efc3c9bcbc)

I didn't see any rules on submitting issues in the repository description, I hope this is acceptable.

**Comment by McKay42** [comment]
> On song select, "mode" and "options" don't draw correctly (the skin uses a wide banner and it is scaled to fit into the small rectangle).

These will never be supported (from my side at least, this is open source so anyone can submit PRs), since the layout does not match exactly and would look like crap. I'm not wasting my time painstakingly getting the songbrowser UI to match stable perfectly.

> In the score screen numbers are reversed (e.g. 81 instead if 18) and are misaligned (probably offset sign error?)
> In game the combo counter only shows the first digit (could be the same bug as above, other digits are drawn off screen).

The problem is that Linux filesystems are CaSe SeNsItIvE by default, while Windows is not. The skin.ini file contains this:
`ComboPrefix:Combo`
But, the actual files included in the skin are named with a lowercase 'c' like this:
`combo-0.png`
So the game can't find the file called e.g. `Combo-0.png` on Linux because it doesn't exist according to the Linux filesystem, so it falls back to loading the default skin (with an incorrect ComboOverlap value coming from the custom skin).

Simply modifying skin.ini with a text editor and replacing the `ComboPrefix:Combo` with `ComboPrefix:combo` fixes the incorrectly drawn score/combo numbers.
