### ISSUE TITLE
Incorrect hitcircle fade in max opacity with HD

### ISSUE THREAD

**Issue by TechnoZamb** [McKay42/McOsu#371]
For ARs < 10 with HD enabled, the maximum opacity reached during the fade in period doesn't quite reach 100% on stable. For example, on AR 3, it reaches 189 / 255 (hitcircle.png is a white square):
![2023-10-21 18-56-05 mpc-hc64](https://github.com/McKay42/McOsu/assets/61671444/0346bbad-e563-481f-aca4-efca9e3991ef)

On McOsu however, it goes all the way to 255:
![2023-10-21 18-59-52 mpc-hc64](https://github.com/McKay42/McOsu/assets/61671444/2ab7a1fe-7ff7-4e9d-8a42-bf41cdd72917)

**Comment by McKay42** [comment]
Huh, and I thought I knew everything about stupid stable behaviors.
I don't understand why this would happen at all, the fading logic is defined like this in stable code:

`hiddenfadein = Transformation(TransformationType.Fade, 0, 1, StartTime - LocalPreEmpt, StartTime - (int)(LocalPreEmpt * 0.6))`
`hiddenfadeout = Transformation(TransformationType.Fade, 1, 0, StartTime - (int)(LocalPreEmpt * 0.6), StartTime - (int)(LocalPreEmpt * 0.3))`

These must reach full opacity by definition, since the fadeout starts exactly when the fadein is finished.
Lazer behaves like stable and has the same math (see [here](https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs)), so there must be something we're missing.

Pinging @Wieku since this affects danser too.

**Comment by McKay42** [comment]
And the explanation is https://github.com/ppy/osu/pull/20572

**Comment by McKay42** [comment]
Will be included in next update, see https://github.com/McKay42/McOsu/commit/9c9230077c993a6cc84ffc04fd082555f2916722
