### ISSUE TITLE
[Bug] somehting with score saving

### ISSUE THREAD

**Issue by majorro** [McKay42/McOsu#374]
Win 10, steam, maps are imported from osu

I choose the map:
![1](https://github.com/McKay42/McOsu/assets/35308665/0f7437be-1a0b-41f5-a860-3c739bc5721d)
Then pass it(tried to reproduce this bug multiple times):
![2](https://github.com/McKay42/McOsu/assets/35308665/2acb9330-611d-48e6-9231-57117ad272e8)
After pressing f5, scores returning to the state from the first picture

The same on other diffs of this mapset, but i was unable to reproduce it on another mapsets

**Comment by McKay42** [comment]
Very rare but sometimes happens: Your osu!stable database contains an old MD5 hash for that beatmap. Since McOsu trusts the initial incoming value, the first time such a problematic beatmap is selected will behave like this, because immediately after the beatmap is selected McOsu recalculates the actual MD5 hash from the file and overwrites the bad old one from the osu!stable database. And now suddenly as soon as the scorebrowser refreshes you can't view old scores anymore because the MD5 changed ("new" beatmap).

The solution is to make osu! fix the MD5 hash in its database by selecting the beatmap there and maybe updating it, maybe re-importing the beatmap, that sort of thing until it works.
