### ISSUE TITLE
The file reading can be done in a more efficient way

### ISSUE THREAD

**Issue by JustAnotherWeeb** [McKay42/McOsu#62]
![slack-imgs com](https://cloud.githubusercontent.com/assets/21132863/17824871/c4a1ba36-6664-11e6-9548-d79e424065d0.png)

You are using i for something that is not an itterable
And you do "x = file.read()" while you can do "with file.read() as x"... allows for deconstruction 'n shit
I'm sorry if I'm wrong but I think that this would be more efficient.

**Comment by McKay42** [comment]
uuuuh, are you sure you added this issue to the correct github repo?
mcosu is written in C++, your image contains python code?

just in case you do mean the file loading in OsuBeatmapDifficulty.cpp, the File class is automatically deleted once it's out of scope because it's a stack object (not allocated with new/malloc/etc.). Declaring the string for holding the current line outside or inside of the loop does not have any performance impact whatsoever.

**Comment by JustAnotherWeeb** [comment]
Oh damn, I clicked on the wrong one.
Case closed, nevermind. haha ^^
Embarrassing.
