### ISSUE TITLE
OpenGL 2.1

### ISSUE THREAD

**Issue by Zero87879** [McKay42/McOsu#91]
Hello there,i have an issue with this,i tried to play/run McOsu,and it says my computer dosent support OpenGL 2.1. Can you please make a version that dosent require OpenGL? and also you should make a Android version.

**Comment by McKay42** [comment]
This is an alpha version, it would be a waste of time for me to make it compatible with ancient hardware atm.
Writing code takes a while, and I also have a few other things I like to do in my free time (feel free to implement an Android backend or DirectX renderer for the engine yourself, since it is open source).
